# Generated by Django 4.1.6 on 2023-04-01 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_doctors_doc_spec'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
